# Generated by .github/workflows/release.yml. Do not edit by hand.
class Mcpwn < Formula
  desc "Security scanner for MCP servers. Flags dangerous tool definitions, hidden instructions, cross-server exfiltration chains, and servers that changed after you approved them"
  homepage "https://github.com/mlab-sh/mcpwn"
  version "1.0.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "1e9988425df179b5badb1b0e25013b55b5ec80ae8f1076ccc84e3fc91aa04424"
    else
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "28b48a4fc1614bf564fd535a27a49e0956b998c04926058fb3080227f6ed69e4"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8707d1f64c10c5f6bf2647d1426c785970a99751d4cc9a11cde6c738080d6115"
    elsif Hardware::CPU.arm?
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c0192f0eb4d6d2a77a4a41de1042825e07953ea731cde6cee9ace00a009c9579"
    end
  end

  def install
    bin.install "mcpwn"
  end

  test do
    assert_match "mcpwn", shell_output("#{bin}/mcpwn --version")
    # Exercises the rule catalogue, so a formula that installs a
    # binary missing its data fails here rather than in the field.
    assert_match "MCPWN-CAP-001", shell_output("#{bin}/mcpwn explain MCPWN-CAP-001")
  end
end
