# Generated by .github/workflows/release.yml. Do not edit by hand.
#
# The checksums below are placeholders: no release has been published yet, so
# there is nothing to hash. The first run of the release workflow overwrites
# this file with the real ones. Until then `brew install` fails loudly on a
# checksum mismatch, which is the intended outcome.
class Mcpwn < Formula
  desc "Security scanner for MCP servers. Flags dangerous tool definitions, hidden instructions, cross-server exfiltration chains, and servers that changed after you approved them"
  homepage "https://github.com/mlab-sh/mcpwn"
  version "1.0.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    else
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    elsif Hardware::CPU.arm?
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "mcpwn"
  end

  test do
    assert_match "mcpwn", shell_output("#{bin}/mcpwn --version")
    # Exercises the rule catalogue, so a formula that installs a binary missing
    # its data fails here rather than in the field.
    assert_match "MCPWN-CAP-001", shell_output("#{bin}/mcpwn explain MCPWN-CAP-001")
  end
end
