# Generated by .github/workflows/release.yml. Do not edit by hand.
class Mcpwn < Formula
  desc "Security scanner for MCP servers. Flags dangerous tool definitions, hidden instructions, cross-server exfiltration chains, and servers that changed after you approved them"
  homepage "https://github.com/mlab-sh/mcpwn"
  version "1.0.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "1f9a6f08b07c374c996d26e6a7f3353249a39f960210ec436b1b54bbd27ce1f2"
    else
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "2c558080afb2d545bad2ce5793fbcea9d6066a784f99630debdf3a7f2132f78b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ec584f0fe3be4756df2a20b2b35e8877c9fd4ab3ed18a3f454dfeba2615b3cc6"
    elsif Hardware::CPU.arm?
      url "https://github.com/mlab-sh/mcpwn/releases/download/v#{version}/mcpwn-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "3c3b9a82ada2dc5b7569cb067849d159cbedcd62749eccf57c10e2e722e41079"
    end
  end

  def install
    bin.install "mcpwn"
  end

  test do
    assert_match "mcpwn", shell_output("#{bin}/mcpwn --version")
    # Exercises the rule catalogue, so a formula that installs a
    # binary missing its data fails here rather than in the field.
    assert_match "MCPWN-CAP-001", shell_output("#{bin}/mcpwn explain MCPWN-CAP-001")
  end
end
